### ISSUE TITLE
Issue with consecutive 'Add to Cart' button clicks

### ISSUE THREAD

**Issue by baralbishwas07** [baralbishwas07/Mero-Store#1]
### Issue Description

There is a problem with the 'Add to Cart' button functionality when clicked consecutively for different products.

### Steps to Reproduce

1. Click the 'Add to Cart' button for one product.
2. Quickly click the 'Add to Cart' button for another product.
3. Notice that the first product's "added to cart" message does not disappear.

### Expected Behavior

Each product's "added to cart" message should disappear after the timeout, even when buttons are clicked consecutively.

### Code Snippet

```javascript
const addedMessage = document.querySelector(`.js-added-to-cart-${productId}`);
addedMessage.classList.add('style-addedMessage');

clearTimeout(timeoutId);
timeoutId = setTimeout(function () {
  addedMessage.classList.remove('style-addedMessage');
}, 2000);

**Comment by iamaakashbasnet** [comment]
Kool
